import { CommonModule, DOCUMENT } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Product, ProductDraft } from './product.model';
import { ProductRepository } from './product.repository';
@Component({selector:'app-products',standalone:true,imports:[CommonModule,ReactiveFormsModule],templateUrl:'./products.html',styleUrls:['../shared/crud.scss']})
export class ProductsComponent{
 protected readonly repo=inject(ProductRepository);private readonly fb=inject(FormBuilder).nonNullable;private readonly doc=inject(DOCUMENT);protected readonly search=signal('');protected readonly category=signal('all');protected readonly editor=signal(false);protected readonly editing=signal<string|null>(null);protected readonly message=signal('');
 protected readonly categories=computed(()=>[...new Set(this.repo.items().map(x=>x.category))].sort());protected readonly filtered=computed(()=>{const q=this.search().toLowerCase().trim();return this.repo.items().filter(x=>(!q||`${x.name} ${x.sku} ${x.barcode}`.toLowerCase().includes(q))&&(this.category()==='all'||x.category===this.category()))});protected readonly active=computed(()=>this.repo.items().filter(x=>x.active).length);protected readonly value=computed(()=>this.repo.items().reduce((a,x)=>a+x.cost,0));
 protected readonly form=this.fb.group({sku:['',[Validators.required,Validators.maxLength(20)]],name:['',[Validators.required,Validators.maxLength(100)]],description:['',[Validators.required,Validators.maxLength(300)]],category:['',Validators.required],salePrice:[0,[Validators.required,Validators.min(0.01)]],cost:[0,[Validators.required,Validators.min(0)]],taxRate:[15,[Validators.required,Validators.min(0),Validators.max(100)]],unit:['unidad',Validators.required],barcode:['',[Validators.required,Validators.pattern(/^\d{8,14}$/)]],supplier:['',Validators.required],active:[true]});
 protected open(item?:Product){this.editing.set(item?.id??null);this.form.reset(item?{...item}:{sku:'',name:'',description:'',category:'',salePrice:0,cost:0,taxRate:15,unit:'unidad',barcode:'',supplier:'',active:true});this.editor.set(true)}protected close(){this.editor.set(false)}protected save(){if(this.form.invalid){this.form.markAllAsTouched();return}const v=this.form.getRawValue();if(this.repo.items().some(x=>x.sku.toLowerCase()===v.sku.trim().toLowerCase()&&x.id!==this.editing()))return void alert('El SKU ya está registrado.');this.repo.save({...v,sku:v.sku.trim().toUpperCase(),name:v.name.trim()} as ProductDraft,this.editing()??undefined);this.close();this.notify('Producto guardado correctamente.')}protected remove(x:Product){if(this.doc.defaultView?.confirm(`¿Eliminar ${x.name}?`)){this.repo.delete(x.id);this.notify('Producto eliminado.')}}protected setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value)}protected setCategory(e:Event){this.category.set((e.target as HTMLSelectElement).value)}private notify(x:string){this.message.set(x);setTimeout(()=>this.message.set(''),2500)}
}
