import { CommonModule, DOCUMENT } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Order, OrderDraft, OrderStatus, PaymentStatus } from './order.model'; import { OrderRepository } from './order.repository';
@Component({selector:'app-orders',standalone:true,imports:[CommonModule,ReactiveFormsModule],templateUrl:'./orders.html',styleUrls:['../shared/crud.scss']})
export class OrdersComponent {
 protected readonly repo=inject(OrderRepository); private readonly fb=inject(FormBuilder).nonNullable; private readonly doc=inject(DOCUMENT); protected readonly search=signal('');protected readonly status=signal('all');protected readonly editor=signal(false);protected readonly editing=signal<string|null>(null);protected readonly message=signal('');
 protected readonly statusLabel:Record<string,string>={pendiente:'Pendiente',confirmado:'Confirmado',produccion:'En producción',listo:'Listo',entregado:'Entregado',cancelado:'Cancelado'};
 protected readonly filtered=computed(()=>{const q=this.search().toLowerCase();return this.repo.items().filter(x=>(!q||`${x.number} ${x.customer} ${x.customerDocument}`.toLowerCase().includes(q))&&(this.status()==='all'||x.status===this.status()))});protected readonly pending=computed(()=>this.repo.items().filter(x=>!['entregado','cancelado'].includes(x.status)).length);protected readonly total=computed(()=>this.repo.items().filter(x=>x.status!=='cancelado').reduce((a,x)=>a+x.total,0));
 protected readonly form=this.fb.group({number:['',Validators.required],customer:['',Validators.required],customerDocument:['',[Validators.required,Validators.pattern(/^\d{10}(\d{3})?$/)]],orderDate:['',Validators.required],deliveryDate:['',Validators.required],status:['pendiente' as OrderStatus,Validators.required],paymentStatus:['pendiente' as PaymentStatus,Validators.required],channel:['Tienda',Validators.required],product:['',Validators.required],quantity:[1,[Validators.required,Validators.min(1)]],unitPrice:[0,[Validators.required,Validators.min(.01)]],discount:[0,[Validators.required,Validators.min(0)]],taxRate:[15,[Validators.required,Validators.min(0),Validators.max(100)]],shipping:[0,[Validators.required,Validators.min(0)]],notes:['',Validators.maxLength(300)]});
 protected readonly estimate=computed(()=>{const v=this.form.getRawValue(),s=v.quantity*v.unitPrice;return s-v.discount+Math.max(0,s-v.discount)*(v.taxRate/100)+v.shipping});
 protected open(x?:Order){this.editing.set(x?.id??null);const line=x?.lines[0];this.form.reset(x?{...x,taxRate:x.taxRate??15,product:line?.product??'',quantity:line?.quantity??1,unitPrice:line?.unitPrice??0}:{number:`PED-${String(this.repo.items().length+1).padStart(3,'0')}`,customer:'',customerDocument:'',orderDate:new Date().toISOString().slice(0,10),deliveryDate:'',status:'pendiente',paymentStatus:'pendiente',channel:'Tienda',product:'',quantity:1,unitPrice:0,discount:0,taxRate:15,shipping:0,notes:''});this.editor.set(true)} protected close(){this.editor.set(false)}
 protected save(){if(this.form.invalid){this.form.markAllAsTouched();return}const v=this.form.getRawValue();if(v.deliveryDate<v.orderDate)return void alert('La entrega no puede ser anterior al pedido.');if(this.repo.items().some(x=>x.number.toLowerCase()===v.number.toLowerCase()&&x.id!==this.editing()))return void alert('El número de pedido ya existe.');const{product,quantity,unitPrice,...rest}=v;this.repo.save({...rest,lines:[{product,quantity,unitPrice}]} as OrderDraft,this.editing()??undefined);this.close();this.notify('Pedido guardado correctamente.')}
 protected remove(x:Order){if(this.doc.defaultView?.confirm(`¿Eliminar ${x.number}?`)){this.repo.delete(x.id);this.notify('Pedido eliminado.')}}protected setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value)}protected setStatus(e:Event){this.status.set((e.target as HTMLSelectElement).value)}protected badge(x:OrderStatus){return x==='cancelado'?'danger':x==='pendiente'?'warn':x==='entregado'?'':'info'}private notify(x:string){this.message.set(x);setTimeout(()=>this.message.set(''),2500)}
}
