import { CommonModule, DOCUMENT } from '@angular/common';import { Component, computed, inject, signal } from '@angular/core';import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';import { InventoryRepository } from '../inventory/inventory.repository';import { OrderRepository } from '../orders/order.repository';import { SaleRepository } from '../sales/sale.repository';import { ReportDefinition, ReportDraft, ReportFormat, ReportFrequency, ReportType } from './report.model';import { ReportRepository } from './report.repository';
@Component({selector:'app-reports',standalone:true,imports:[CommonModule,ReactiveFormsModule],templateUrl:'./reports.html',styleUrls:['../shared/crud.scss','./reports.scss']})
export class ReportsComponent {
 protected readonly repo=inject(ReportRepository);protected readonly sales=inject(SaleRepository);protected readonly orders=inject(OrderRepository);protected readonly inventory=inject(InventoryRepository);private readonly fb=inject(FormBuilder).nonNullable;private readonly doc=inject(DOCUMENT);protected readonly search=signal('');protected readonly type=signal('all');protected readonly editor=signal(false);protected readonly editing=signal<string|null>(null);protected readonly message=signal('');
 protected readonly filtered=computed(()=>{const q=this.search().toLowerCase();return this.repo.items().filter(x=>(!q||`${x.name} ${x.type} ${x.format}`.toLowerCase().includes(q))&&(this.type()==='all'||x.type===this.type()))});protected readonly revenue=computed(()=>this.sales.items().filter(x=>x.status!=='anulada').reduce((a,x)=>a+x.total,0));protected readonly lowStock=computed(()=>this.inventory.items().filter(x=>x.stock<=x.minimumStock).length);
 protected readonly form=this.fb.group({name:['',[Validators.required,Validators.maxLength(100)]],type:['ventas' as ReportType,Validators.required],dateFrom:['',Validators.required],dateTo:['',Validators.required],format:['CSV' as ReportFormat,Validators.required],frequency:['manual' as ReportFrequency,Validators.required],includeTax:[true],notes:['',Validators.maxLength(300)],active:[true]});
 protected open(x?:ReportDefinition){this.editing.set(x?.id??null);const today=new Date().toISOString().slice(0,10);this.form.reset(x?{...x}:{name:'',type:'ventas',dateFrom:today.slice(0,8)+'01',dateTo:today,format:'CSV',frequency:'manual',includeTax:true,notes:'',active:true});this.editor.set(true)}protected close(){this.editor.set(false)}protected save(){if(this.form.invalid){this.form.markAllAsTouched();return}const v=this.form.getRawValue();if(v.dateTo<v.dateFrom)return void alert('La fecha final no puede ser anterior a la inicial.');this.repo.save(v as ReportDraft,this.editing()??undefined);this.close();this.notify('Configuración de reporte guardada.')}protected remove(x:ReportDefinition){if(this.doc.defaultView?.confirm(`¿Eliminar el reporte ${x.name}?`)){this.repo.delete(x.id);this.notify('Reporte eliminado.')}}
 protected export(x:ReportDefinition){const rows=this.buildRows(x.type),csv=rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n'),url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=this.doc.createElement('a');a.href=url;a.download=`${x.name.toLowerCase().replaceAll(' ','-')}.csv`;a.click();URL.revokeObjectURL(url);this.notify('Reporte generado en CSV.')}
 private buildRows(type:string):(string|number)[][]{if(type==='ventas'||type==='rentabilidad')return[['Comprobante','Cliente','Fecha','Subtotal','Impuesto','Total'],...this.sales.items().map(x=>[x.invoiceNumber,x.customer,x.issueDate,x.subtotal,x.tax,x.total])];if(type==='pedidos')return[['Pedido','Cliente','Estado','Entrega','Total'],...this.orders.items().map(x=>[x.number,x.customer,x.status,x.deliveryDate,x.total])];if(type==='inventario')return[['SKU','Producto','Stock','Mínimo','Ubicación'],...this.inventory.items().map(x=>[x.sku,x.name,x.stock,x.minimumStock,x.location])];return[['Indicador','Valor'],['Clientes registrados','Consulte el módulo Clientes']]}protected setSearch(e:Event){this.search.set((e.target as HTMLInputElement).value)}protected setType(e:Event){this.type.set((e.target as HTMLSelectElement).value)}private notify(x:string){this.message.set(x);setTimeout(()=>this.message.set(''),2500)}
}
